# File: .github/workflows/refresh.yml
name: Refresh

on: workflow_dispatch

jobs:
  refresh:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger GitHub pages rebuild
        run: |
          curl --fail --request POST \
            --url https://api.github.com/repos/${{ github.repository }}/pages/builds \
            --header "Accept: application/vnd.github.v3+json"
